### ISSUE TITLE
Output directory?

### ISSUE THREAD

**Issue by jacobkossman** [AlleyFord/schematic#1]
Hey! This looks super cool / promising and I want to look into it further. However on first glance it doesn't seem like there's a way to specify an output directory? I'm using Shopify CLI and I'm worried about breaking themes when it uploads non-replaced schema. I'm hoping there's a way to have something like a src folder for the sections as well? Maybe I'm just overlooking something but if you could provide an example of how to use "properly" with Shopify CLI that'd be sweet. Thanks!

**Comment by josho** [comment]
Sure! It works directly on the theme files, so you should be able to run it from the theme's root directory. By default, it looks for schema files in `src/schema`. 
![image](https://user-images.githubusercontent.com/386722/222556339-0688f276-1128-459a-8e28-8caec0229cf8.png)

**Comment by jacobkossman** [comment]
I mean is there a way to have both the final output files, the schema config files and the schematic marked up with comments all coexist? i'm just confused as to how you can update the schema if it compiles directly in the same file?

or now i'm thinking about it: does the comment added at the bottom always stay there? and the schema is regenerated above? i haven't had a chance to install and test yet.

**Comment by josho** [comment]
Oh yeah, sorry for the confusion! And yeah, it'll stick the generated schema directly below the magic comment itself in each file directly. I should make that more clear, or maybe an option, cuz it's a little scary trusting something to hack on your files directly.

And good catch on `schema-utils`, it's marked as a dev dependency in the repo and not a dependency. That's my bad! Will update.

Glad you dig it. It's 100% essential for any Shopify dev work I do now!
